# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'ko-kr'
    sources:
      - src/Korean.dic
      - src/additional_words.txt
      - src/hunspell/index.dic
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: 'true'
    compress: false
checksumFile: true
